import React, {
  createContext,
  useContext,
  useState,
  useEffect,
  ReactNode,
} from "react";

export type Language = "en" | "vi" | "zh" | "ja" | "ko" | "th" | "fr" | "es";

export interface LanguageOption {
  code: Language;
  name: string;
  nativeName: string;
  flag: string;
}

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  { code: "en", name: "English", nativeName: "English", flag: "🇺🇸" },
  { code: "vi", name: "Vietnamese", nativeName: "Tiếng Việt", flag: "🇻🇳" },
  { code: "zh", name: "Chinese", nativeName: "中文", flag: "🇨🇳" },
  { code: "ja", name: "Japanese", nativeName: "日本語", flag: "🇯🇵" },
  { code: "ko", name: "Korean", nativeName: "한국어", flag: "🇰🇷" },
  { code: "th", name: "Thai", nativeName: "ภาษาไทย", flag: "🇹🇭" },
  { code: "fr", name: "French", nativeName: "Français", flag: "🇫🇷" },
  { code: "es", name: "Spanish", nativeName: "Español", flag: "🇪🇸" },
];

interface LanguageContextType {
  currentLanguage: Language;
  setLanguage: (language: Language) => void;
  t: (key: string, fallback?: string) => string;
  getCurrentLanguageInfo: () => LanguageOption;
}

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined,
);

const STORAGE_KEY = "td_consulting_language";

// Translation function
const useTranslations = (language: Language) => {
  const translations: Record<Language, Record<string, string>> = {
    en: {
      // Navigation
      "nav.dashboard": "Dashboard",
      "nav.jobs": "Jobs",
      "nav.candidates": "Candidates",
      "nav.calendar": "Calendar",
      "nav.email": "Email Automation",
      "nav.reports": "Reports",
      "nav.notifications": "Notifications",
      "nav.settings": "Settings",

      // Header
      "header.search": "Search candidates, jobs...",
      "header.quickAdd": "Quick Add",
      "header.addJob": "Add Job",
      "header.addCandidate": "Add Candidate",
      "header.language": "Language",

      // Dashboard
      "dashboard.title": "Dashboard",
      "dashboard.subtitle":
        "Welcome back! Here's an overview of your recruitment activities.",
      "dashboard.activeJobs": "Active Jobs",
      "dashboard.totalCandidates": "Total Candidates",
      "dashboard.interviewsThisWeek": "Interviews This Week",
      "dashboard.avgTimeToHire": "Avg. Time to Hire",
      "dashboard.totalRevenue": "Total Revenue",
      "dashboard.recentJobs": "Recent Jobs",
      "dashboard.topCandidates": "Top Candidates",
      "dashboard.recentActivity": "Recent Activity",
      "dashboard.viewAll": "View All",

      // Jobs
      "jobs.title": "Jobs",
      "jobs.subtitle":
        "Manage job postings, track applications, and monitor hiring progress.",
      "jobs.createJob": "Create Job",
      "jobs.filterJobs": "Filter Jobs",
      "jobs.position": "Position",
      "jobs.department": "Department",
      "jobs.applications": "Applications",
      "jobs.status": "Status",
      "jobs.deadline": "Deadline",
      "jobs.performance": "Performance",
      "jobs.recruiter": "Recruiter",
      "jobs.location": "Location",
      "jobs.priority": "Priority",

      // Candidates
      "candidates.title": "Candidates",
      "candidates.subtitle":
        "Manage candidate profiles, track progress, and schedule interviews.",
      "candidates.addCandidate": "Add Candidate",
      "candidates.moreFilters": "More Filters",
      "candidates.name": "Name",
      "candidates.position": "Position",
      "candidates.stage": "Stage",
      "candidates.rating": "Rating",
      "candidates.appliedDate": "Applied Date",
      "candidates.source": "Source",

      // Email Automation
      "email.title": "Email Automation",
      "email.subtitle":
        "Manage email templates, workflows, and automate candidate communication.",
      "email.newWorkflow": "New Workflow",
      "email.newTemplate": "New Template",
      "email.activeTemplates": "Active Templates",
      "email.emailsSent": "Emails Sent (30d)",
      "email.avgOpenRate": "Avg. Open Rate",
      "email.activeWorkflows": "Active Workflows",
      "email.templates": "Email Templates",
      "email.workflows": "Automation Workflows",
      "email.analytics": "Analytics",
      "email.settings": "Settings",

      // Calendar
      "calendar.title": "Calendar",
      "calendar.subtitle":
        "Schedule interviews, meetings, and track all your appointments.",
      "calendar.scheduleEvent": "Schedule Event",
      "calendar.filterEvents": "Filter Events",
      "calendar.month": "Month",
      "calendar.week": "Week",
      "calendar.day": "Day",
      "calendar.todaySchedule": "Today's Schedule",
      "calendar.upcomingEvents": "Upcoming Events",
      "calendar.eventTypes": "Event Types",

      // Reports
      "reports.title": "Reports",
      "reports.subtitle":
        "Analyze recruitment performance and generate insights.",
      "reports.overview": "Overview",
      "reports.performance": "Performance",
      "reports.sources": "Sources",
      "reports.advanced": "Advanced",
      "reports.exportReport": "Export Report",
      "reports.dateRange": "Date Range",

      // Notifications
      "notifications.title": "Notifications",
      "notifications.subtitle":
        "Stay updated with important recruitment activities and system alerts.",
      "notifications.markAllRead": "Mark All as Read",
      "notifications.filter": "Filter",
      "notifications.noNotifications": "No notifications",

      // Settings
      "settings.title": "Settings",
      "settings.subtitle":
        "Manage your account, preferences, and system configuration.",
      "settings.profile": "Profile",
      "settings.notifications": "Notifications",
      "settings.appearance": "Appearance",
      "settings.security": "Security",
      "settings.integrations": "Integrations",
      "settings.organization": "Organization",
      "settings.personalInfo": "Personal Information",
      "settings.preferences": "Preferences",
      "settings.language": "Language",
      "settings.firstName": "First Name",
      "settings.lastName": "Last Name",
      "settings.email": "Email Address",
      "settings.phone": "Phone Number",
      "settings.jobTitle": "Job Title",
      "settings.department": "Department",
      "settings.saveChanges": "Save Changes",
      "settings.changePhoto": "Change Photo",
      "settings.remove": "Remove",
      "settings.exportSettings": "Export Settings",
      "settings.importSettings": "Import Settings",

      // Common
      "common.loading": "Loading...",
      "common.save": "Save",
      "common.cancel": "Cancel",
      "common.edit": "Edit",
      "common.delete": "Delete",
      "common.add": "Add",
      "common.search": "Search",
      "common.filter": "Filter",
      "common.export": "Export",
      "common.import": "Import",
      "common.create": "Create",
      "common.update": "Update",
      "common.close": "Close",
      "common.back": "Back",
      "common.next": "Next",
      "common.previous": "Previous",
      "common.yes": "Yes",
      "common.no": "No",
      "common.actions": "Actions",
      "common.details": "Details",
      "common.view": "View",
      "common.manage": "Manage",

      // Dashboard Hardcoded Text
      "dashboard.filter": "Filter",
      "dashboard.newJob": "New Job",
      "dashboard.vsLastMonth": "vs last month",
      "dashboard.recruitmentPipeline": "Recruitment Pipeline",
      "dashboard.quickStats": "Quick Stats",
      "dashboard.costPerHire": "Cost per Hire",
      "dashboard.hiringSuccessRate": "Hiring Success Rate",
      "dashboard.sourceEffectiveness": "Source Effectiveness",
      "dashboard.pendingInterviews": "Pending Interviews",
      "dashboard.recentJobPostings": "Recent Job Postings",
      "dashboard.jobTitle": "Job Title",
      "dashboard.department": "Department",
      "dashboard.applicants": "Applicants",
      "dashboard.status": "Status",
      "dashboard.priority": "Priority",
      "dashboard.active": "Active",
      "dashboard.draft": "Draft",
      "dashboard.high": "High",
      "dashboard.medium": "Medium",
      "dashboard.low": "Low",
      "dashboard.applied": "Applied",
      "dashboard.screening": "Screening",
      "dashboard.interview": "Interview",
      "dashboard.offer": "Offer",
      "dashboard.hired": "Hired",

      // Candidates Page
      "candidates.totalCandidates": "Total Candidates",
      "candidates.activePipeline": "Active Pipeline",
      "candidates.interviewsScheduled": "Interviews Scheduled",
      "candidates.offersExtended": "Offers Extended",
      "candidates.list": "List",
      "candidates.grid": "Grid",
      "candidates.fields": "Fields",
      "candidates.searchPlaceholder":
        "Search candidates by name, position, skills...",
      "candidates.allDepartments": "All Departments",
      "candidates.allStages": "All Stages",
      "candidates.allRecruiters": "All Recruiters",
      "candidates.candidateName": "Candidate Name",
      "candidates.appliedOn": "Applied On",
      "candidates.email": "Email",
      "candidates.phone": "Phone",
      "candidates.jobPosition": "Job Position",
      "candidates.recruiter": "Recruiter",
      "candidates.currentStage": "Current Stage",
      "candidates.source": "Source",
      "candidates.salary": "Salary",
      "candidates.location": "Location",
      "candidates.actions": "Actions",
      "candidates.viewDetails": "View Details",
      "candidates.editCandidate": "Edit Candidate",
      "candidates.downloadCV": "Download CV",
      "candidates.shareProfile": "Share Profile",
      "candidates.removeCandidate": "Remove Candidate",
      "candidates.noCandidates": "No candidates",
      "candidates.previous": "Previous",
      "candidates.next": "Next",
      "candidates.fullName": "Full Name",
      "candidates.city": "City, State",
      "candidates.selectPosition": "Select position",
      "candidates.selectDepartment": "Select department",
      "candidates.selectSource": "Select source",
      "candidates.uploadResume": "Upload Resume/CV",
      "candidates.automaticExtraction":
        "We'll automatically extract candidate information from the resume",
      "candidates.chooseFile": "Choose File",
      "candidates.chooseFiles": "Choose Files",
      "candidates.singleResume": "Single Resume",
      "candidates.multipleResumes": "Multiple Resumes",
      "candidates.uploadResumes": "Upload Resumes/CVs",
      "candidates.uploadMultiple":
        "Upload multiple resumes and assign them to a single job position",
      "candidates.selectPositionAll": "Select position for all resumes",
      "candidates.selectSourceAll":
        "Select position for all resumes (Optional)",
      "candidates.uploadedFiles": "Uploaded Files",
      "candidates.createCandidate": "Create Candidate",
      "candidates.createCandidates": "Create Candidates",
      "candidates.manualEntry": "Manual Entry",
      "candidates.uploadResumeTab": "Upload Resume",
      "candidates.addNewCandidate": "Add New Candidate",
      "candidates.createCandidateProfile":
        "Create a new candidate profile manually or upload their resume.",
      "candidates.experienceLevel": "Experience Level",
      "candidates.anyExperience": "Any experience",
      "candidates.entryLevel": "Entry Level (0-2 years)",
      "candidates.midLevel": "Mid Level (3-5 years)",
      "candidates.seniorLevel": "Senior Level (5+ years)",
      "candidates.salaryRange": "Salary Range",
      "candidates.anySalary": "Any salary",
      "candidates.50to75k": "$50k - $75k",
      "candidates.75to100k": "$75k - $100k",
      "candidates.100to150k": "$100k - $150k",
      "candidates.150kPlus": "$150k+",
      "candidates.rating": "Rating",
      "candidates.anyRating": "Any rating",
      "candidates.5stars": "5 Stars",
      "candidates.4plusStars": "4+ Stars",
      "candidates.3plusStars": "3+ Stars",
      "candidates.applicationDate": "Application Date",
      "candidates.anyDate": "Any date",
      "candidates.lastWeek": "Last Week",
      "candidates.lastMonth": "Last Month",
      "candidates.lastQuarter": "Last Quarter",
      "candidates.skills": "Skills",
      "candidates.searchBySkills": "Search by specific skills...",
      "candidates.applyFilters": "Apply Filters",
      "candidates.filtersApplied": "Filters Applied",
      "candidates.advancedFiltersDescription":
        "Advanced filters have been applied to the candidate list.",
      "candidates.advancedFilters": "Advanced Filters",
      "candidates.additionalFilters":
        "Apply additional filters to refine your candidate search.",
      "candidates.daysInStage": "days in stage",

      // Jobs Page
      "jobs.activeJobs": "Active Jobs",
      "jobs.totalApplications": "Total Applications",
      "jobs.positionsFilled": "Positions Filled",
      "jobs.avgTimeToFill": "Avg. Time to Fill",
      "jobs.days": "days",
      "jobs.exportReport": "Export Report",
      "jobs.addNewJob": "Add New Job",
      "jobs.columns": "Columns",
      "jobs.searchJobs": "Search jobs by position, department, recruiter...",
      "jobs.allStatus": "All Status",
      "jobs.open": "Open",
      "jobs.closed": "Closed",
      "jobs.inProgress": "In Progress",
      "jobs.paused": "Paused",
      "jobs.allPriority": "All Priority",
      "jobs.moreFilters": "More Filters",
      "jobs.target": "Target",
      "jobs.process": "Process",
      "jobs.openDate": "Open Date",
      "jobs.deadline": "Deadline",
      "jobs.estimatedCost": "Est. Cost",
      "jobs.actualCost": "Actual Cost",
      "jobs.editJob": "Edit Job",
      "jobs.share": "Share",
      "jobs.delete": "Delete",
      "jobs.deleteJob": "Delete Job",
      "jobs.confirmDelete":
        'Are you sure you want to delete "{position}"? This action cannot be undone.',
      "jobs.jobCreated": "Job Created",
      "jobs.jobCreatedDesc": '"{position}" has been successfully created.',
      "jobs.jobUpdated": "Job Updated",
      "jobs.jobUpdatedDesc": '"{position}" has been successfully updated.',
      "jobs.jobDeleted": "Job Deleted",
      "jobs.jobDeletedDesc": "The job has been successfully deleted.",
      "jobs.error": "Error",
      "jobs.createError": "Failed to create job. Please try again.",
      "jobs.updateError": "Failed to update job. Please try again.",
      "jobs.deleteError": "Failed to delete job. Please try again.",
      "jobs.shareJob": "Share Job",
      "jobs.generateLink": "Generate a shareable link for this job posting.",
      "jobs.linkCopied": "Link Copied",
      "jobs.linkCopiedDesc": "Job sharing link has been copied to clipboard.",
      "jobs.copy": "Copy",
      "jobs.close": "Close",
      "jobs.addNewJobTitle": "Add New Job",
      "jobs.editJobTitle": "Edit Job",
      "jobs.updateJobDetails": "Update the job details below.",
      "jobs.createJobDetails":
        "Create a new job posting with all the necessary details.",
      "jobs.basicInfo": "Basic Info",
      "jobs.jobDetails": "Job Details",
      "jobs.teamBudget": "Team & Budget",
      "jobs.emailAlias": "Email Alias",
      "jobs.emailPlaceholder": "jobs@company.com",
      "jobs.jobLocation": "Job Location",
      "jobs.locationPlaceholder": "San Francisco, CA or Remote",
      "jobs.positionPlaceholder": "Senior Software Engineer",
      "jobs.employmentType": "Employment Type",
      "jobs.selectEmploymentType": "Select employment type",
      "jobs.fullTime": "Full-time",
      "jobs.partTime": "Part-time",
      "jobs.contract": "Contract",
      "jobs.domainIndustry": "Domain/Industry",
      "jobs.domainPlaceholder": "Technology, Finance, Healthcare",
      "jobs.selectPriority": "Select priority",
      "jobs.expectedSkills": "Expected Skills",
      "jobs.skillsPlaceholder": "React, TypeScript, Node.js (comma separated)",
      "jobs.salaryMin": "Salary Min",
      "jobs.salaryMax": "Salary Max",
      "jobs.jobDescription": "Job Description",
      "jobs.descriptionPlaceholder":
        "Describe the role, responsibilities, and requirements...",
      "jobs.headcount": "Headcount",
      "jobs.selectRecruiter": "Select recruiter",
      "jobs.interviewers": "Interviewers",
      "jobs.interviewersPlaceholder":
        "Select team members who will conduct interviews",
      "jobs.estimatedBudget": "Estimated Budget",
      "jobs.createJob": "Create Job",
      "jobs.updateJob": "Update Job",
      "jobs.pipelineSummary": "Pipeline Summary",
      "jobs.interviewing": "Interviewing",
      "jobs.applied": "Applied",
      "jobs.interview": "Interview",
      "jobs.hired": "Hired",

      // Calendar Page
      "calendar.filterEvents": "Filter Events",
      "calendar.scheduleEvent": "Schedule Event",
      "calendar.scheduleNewEvent": "Schedule New Event",
      "calendar.createEvent":
        "Create a new interview, meeting, or appointment.",
      "calendar.eventType": "Event Type",
      "calendar.selectType": "Select type",
      "calendar.technicalInterview": "Technical Interview",
      "calendar.phoneScreening": "Phone Screening",
      "calendar.finalRound": "Final Round",
      "calendar.teamMeeting": "Team Meeting",
      "calendar.offerDiscussion": "Offer Discussion",
      "calendar.meetingType": "Meeting Type",
      "calendar.selectFormat": "Select format",
      "calendar.inPerson": "In Person",
      "calendar.videoCall": "Video Call",
      "calendar.phoneCall": "Phone Call",
      "calendar.eventTitle": "Event Title",
      "calendar.eventTitlePlaceholder": "e.g. Technical Interview - John Doe",
      "calendar.date": "Date",
      "calendar.duration": "Duration",
      "calendar.selectDuration": "Select duration",
      "calendar.15minutes": "15 minutes",
      "calendar.30minutes": "30 minutes",
      "calendar.45minutes": "45 minutes",
      "calendar.1hour": "1 hour",
      "calendar.1point5hours": "1.5 hours",
      "calendar.2hours": "2 hours",
      "calendar.startTime": "Start Time",
      "calendar.locationLink": "Location/Link",
      "calendar.locationPlaceholder": "Conference Room A or Zoom link",
      "calendar.participants": "Participants",
      "calendar.participantsPlaceholder": "Add attendees by email",
      "calendar.notes": "Notes",
      "calendar.notesPlaceholder": "Additional notes or agenda items...",
      "calendar.january2024": "January 2024",
      "calendar.month": "Month",
      "calendar.week": "Week",
      "calendar.day": "Day",
      "calendar.sun": "Sun",
      "calendar.mon": "Mon",
      "calendar.tue": "Tue",
      "calendar.wed": "Wed",
      "calendar.thu": "Thu",
      "calendar.fri": "Fri",
      "calendar.sat": "Sat",
      "calendar.noEvents": "No events",
      "calendar.todaySchedule": "Today's Schedule",
      "calendar.totalEvents": "Total Events",
      "calendar.interviews": "Interviews",
      "calendar.meetings": "Meetings",
      "calendar.freeTime": "Free Time",
      "calendar.4hours": "4 hours",
      "calendar.upcomingEvents": "Upcoming Events",
      "calendar.editEvent": "Edit Event",
      "calendar.viewAttendees": "View Attendees",
      "calendar.cancelEvent": "Cancel Event",
      "calendar.eventTypes": "Event Types",
      "calendar.eventsOn": "Events on {date}",

      // Email Automation Page
      "email.newWorkflow": "New Workflow",
      "email.newTemplate": "New Template",
      "email.createEmailWorkflow": "Create Email Workflow",
      "email.setupAutomatedSequence":
        "Set up an automated email sequence for candidates.",
      "email.workflowName": "Workflow Name",
      "email.workflowNamePlaceholder": "e.g. Interview Follow-up",
      "email.triggerEvent": "Trigger Event",
      "email.selectTrigger": "Select trigger",
      "email.applicationReceived": "Application Received",
      "email.screeningCompleted": "Screening Completed",
      "email.interviewScheduled": "Interview Scheduled",
      "email.offerExtended": "Offer Extended",
      "email.applicationRejected": "Application Rejected",
      "email.description": "Description",
      "email.descriptionPlaceholder": "Brief description of this workflow...",
      "email.createWorkflow": "Create Workflow",
      "email.createEmailTemplate": "Create Email Template",
      "email.createTemplateDesc":
        "Create a new email template for candidate communication.",
      "email.templateName": "Template Name",
      "email.templateNamePlaceholder": "e.g. Interview Confirmation",
      "email.templateType": "Template Type",
      "email.selectType": "Select type",
      "email.autoResponse": "Auto Response",
      "email.interviewRelated": "Interview Related",
      "email.jobOffer": "Job Offer",
      "email.rejection": "Rejection",
      "email.reminder": "Reminder",
      "email.followUp": "Follow-up",
      "email.subjectLine": "Subject Line",
      "email.subjectPlaceholder":
        "e.g. Interview scheduled for {{job_title}} position",
      "email.emailContent": "Email Content",
      "email.contentPlaceholder":
        "Dear {{candidate_name}},\n\nYour email content here...\n\nBest regards,\n{{company_name}} Team",
      "email.availableVariables": "Available Variables",
      "email.createTemplate": "Create Template",
      "email.emailTemplates": "Email Templates",
      "email.automationWorkflows": "Automation Workflows",
      "email.analytics": "Analytics",
      "email.settings": "Settings",
      "email.active": "Active",
      "email.usage30d": "Usage (30d):",
      "email.openRate": "Open Rate:",
      "email.trigger": "Trigger:",
      "email.edit": "Edit",
      "email.editEmailTemplate": "Edit Email Template",
      "email.updateTemplate":
        "Update your email template content and settings.",
      "email.saveChanges": "Save Changes",
      "email.steps": "Steps",
      "email.activeCandidates": "Active Candidates",
      "email.emailPerformance": "Email Performance",
      "email.totalEmailsSent": "Total Emails Sent",
      "email.averageOpenRate": "Average Open Rate",
      "email.averageClickRate": "Average Click Rate",
      "email.bounceRate": "Bounce Rate",
      "email.topPerformingTemplates": "Top Performing Templates",
      "email.sent": "sent",
      "email.open": "open",
      "email.emailSettings": "Email Settings",
      "email.autoSendAcknowledgments": "Auto-send acknowledgments",
      "email.autoSendDesc":
        "Automatically send confirmation emails when candidates apply",
      "email.interviewReminders": "Interview reminders",
      "email.reminderDesc": "Send reminder emails 24 hours before interviews",
      "email.statusChangeNotifications": "Status change notifications",
      "email.statusChangeDesc":
        "Notify candidates when their application status changes",
      "email.senderInformation": "Sender Information",
      "email.fromName": "From Name",
      "email.fromEmail": "From Email",
      "email.replyToEmail": "Reply-to Email",
      "email.saveSettings": "Save Settings",

      // Reports Page
      "reports.exportReport": "Export Report",
      "reports.dateRange": "Date Range",
      "reports.last7days": "Last 7 days",
      "reports.last30days": "Last 30 days",
      "reports.last90days": "Last 90 days",
      "reports.lastYear": "Last year",
      "reports.job": "Job",
      "reports.allJobs": "All Jobs",
      "reports.recruiter": "Recruiter",
      "reports.allRecruiters": "All Recruiters",
      "reports.totalApplications": "Total Applications",
      "reports.conversionRate": "Conversion Rate",
      "reports.avgTimeToHire": "Avg. Time to Hire",
      "reports.costPerHire": "Cost per Hire",
      "reports.conversionFunnel": "Conversion Funnel",
      "reports.monthlyTrends": "Monthly Trends",
      "reports.recruiterPerformance": "Recruiter Performance",
      "reports.jobPerformanceComparison": "Job Performance Comparison",
      "reports.detailedRecruiterMetrics": "Detailed Recruiter Metrics",
      "reports.effectivenessScore": "Effectiveness Score",
      "reports.applicationSources": "Application Sources",
      "reports.sourceEffectiveness": "Source Effectiveness",
      "reports.sourcePerformanceDetails": "Source Performance Details",
      "reports.effective": "Effective",
      "reports.applicationFrequencyHeatmap": "Application Frequency Heatmap",
      "reports.monday": "Monday",
      "reports.tuesday": "Tuesday",
      "reports.wednesday": "Wednesday",
      "reports.thursday": "Thursday",
      "reports.friday": "Friday",
      "reports.9am": "9 AM",
      "reports.2pm": "2 PM",
      "reports.pipelineVelocity": "Pipeline Velocity",
      "reports.averageStageDuration": "Average stage duration",
      "reports.screeningToInterview": "Screening → Interview",
      "reports.interviewToOffer": "Interview → Offer",
      "reports.qualityScore": "Quality Score",
      "reports.candidateQualityRating": "Candidate quality rating",
      "reports.quality": "Quality",
      "reports.automationRate": "Automation Rate",
      "reports.automatedCommunications": "Automated communications",
      "reports.emailResponses": "Email responses",
      "reports.stageUpdates": "Stage updates",
      "reports.applications": "applications",
      "reports.interviews": "interviews",
      "reports.hires": "hires",
      "reports.jobA": "Job A",
      "reports.jobB": "Job B",
      "reports.applicationVolume": "Application Volume",
      "reports.qualityScoreRadar": "Quality Score",
      "reports.timeToFill": "Time to Fill",
      "reports.costEfficiency": "Cost Efficiency",
      "reports.candidateSatisfaction": "Candidate Satisfaction",
      "reports.applications": "Applications",
      "reports.interviews": "Interviews",
      "reports.hires": "Hires",
      "reports.effectivenessPercent": "Effectiveness %",
      "reports.days": "days",

      // Settings Page
      "settings.personalInfo": "Personal Information",
      "settings.changePhoto": "Change Photo",
      "settings.remove": "Remove",
      "settings.firstName": "First Name",
      "settings.lastName": "Last Name",
      "settings.emailAddress": "Email Address",
      "settings.phoneNumber": "Phone Number",
      "settings.jobTitle": "Job Title",
      "settings.humanResources": "Human Resources",
      "settings.engineering": "Engineering",
      "settings.product": "Product",
      "settings.design": "Design",
      "settings.marketing": "Marketing",
      "settings.saveChanges": "Save Changes",
      "settings.preferences": "Preferences",
      "settings.timezone": "Timezone",
      "settings.pacificStandardTime": "Pacific Standard Time",
      "settings.easternStandardTime": "Eastern Standard Time",
      "settings.centralStandardTime": "Central Standard Time",
      "settings.mountainStandardTime": "Mountain Standard Time",
      "settings.utc": "UTC",
      "settings.dateFormat": "Date Format",
      "settings.currency": "Currency",
      "settings.autoSaveDrafts": "Auto-save drafts",
      "settings.autoSaveDesc": "Automatically save form drafts",
      "settings.savePreferences": "Save Preferences",
      "settings.notificationSettings": "Notification Settings",
      "settings.emailNotifications": "Email Notifications",
      "settings.newApplications": "New Applications",
      "settings.newApplicationsDesc": "Get notified when candidates apply",
      "settings.interviewReminders": "Interview Reminders",
      "settings.interviewRemindersDesc": "Reminders 24 hours before interviews",
      "settings.statusUpdates": "Status Updates",
      "settings.statusUpdatesDesc": "When candidate status changes",
      "settings.weeklyReports": "Weekly Reports",
      "settings.weeklyReportsDesc": "Summary of recruitment activities",
      "settings.pushNotifications": "Push Notifications",
      "settings.urgentUpdates": "Urgent Updates",
      "settings.urgentUpdatesDesc": "Critical system alerts and updates",
      "settings.calendarEvents": "Calendar Events",
      "settings.calendarEventsDesc": "Upcoming interviews and meetings",
      "settings.teamMessages": "Team Messages",
      "settings.teamMessagesDesc": "Messages from team members",
      "settings.notificationFrequency": "Notification Frequency",
      "settings.emailDigest": "Email Digest",
      "settings.realTime": "Real-time",
      "settings.hourly": "Hourly",
      "settings.daily": "Daily",
      "settings.weekly": "Weekly",
      "settings.never": "Never",
      "settings.appearanceTheme": "Appearance & Theme",
      "settings.theme": "Theme",
      "settings.light": "Light",
      "settings.dark": "Dark",
      "settings.system": "System",
      "settings.layout": "Layout",
      "settings.compactMode": "Compact Mode",
      "settings.compactModeDesc": "Reduce spacing for more content",
      "settings.showSidebar": "Show Sidebar",
      "settings.showSidebarDesc": "Always show navigation sidebar",
      "settings.fontSettings": "Font Settings",
      "settings.fontSize": "Font Size",
      "settings.small": "Small",
      "settings.large": "Large",
      "settings.securitySettings": "Security Settings",
      "settings.currentPassword": "Current Password",
      "settings.newPassword": "New Password",
      "settings.confirmNewPassword": "Confirm New Password",
      "settings.updatePassword": "Update Password",
      "settings.twoFactorAuth": "Two-Factor Authentication",
      "settings.2faStatus": "2FA Status",
      "settings.2faDesc": "Enhance account security",
      "settings.disabled": "Disabled",
      "settings.enable2fa": "Enable 2FA",
      "settings.activeSessions": "Active Sessions",
      "settings.currentSession": "Current Session",
      "settings.chromeOnMacos": "Chrome on macOS",
      "settings.thirdPartyIntegrations": "Third-Party Integrations",
      "settings.googleCalendar": "Google Calendar",
      "settings.googleCalendarDesc": "Sync interviews and meetings",
      "settings.slack": "Slack",
      "settings.slackDesc": "Team notifications and updates",
      "settings.zoom": "Zoom",
      "settings.zoomDesc": "Video interview integration",
      "settings.linkedin": "LinkedIn",
      "settings.linkedinDesc": "Import candidate profiles",
      "settings.github": "GitHub",
      "settings.githubDesc": "Technical assessment integration",
      "settings.microsoftTeams": "Microsoft Teams",
      "settings.microsoftTeamsDesc": "Alternative video meeting platform",
      "settings.connected": "Connected",
      "settings.disconnected": "Disconnected",
      "settings.connect": "Connect",
      "settings.disconnect": "Disconnect",
      "settings.organizationSettings": "Organization Settings",
      "settings.companyName": "Company Name",
      "settings.companyWebsite": "Company Website",
      "settings.companySize": "Company Size",
      "settings.1to10employees": "1-10 employees",
      "settings.11to50employees": "11-50 employees",
      "settings.50to200employees": "50-200 employees",
      "settings.200to1000employees": "200-1000 employees",
      "settings.1000plusEmployees": "1000+ employees",
      "settings.industry": "Industry",
      "settings.technology": "Technology",
      "settings.finance": "Finance",
      "settings.healthcare": "Healthcare",
      "settings.education": "Education",
      "settings.retail": "Retail",
      "settings.other": "Other",
      "settings.saveOrganizationSettings": "Save Organization Settings",
      "settings.teamManagement": "Team Management",
      "settings.teamMembers": "Team Members",
      "settings.teamMembersDesc": "Manage user access and permissions",
      "settings.inviteMember": "Invite Member",
      "settings.admin": "Admin",

      // Common UI Elements
      "common.loading": "Loading...",
      "common.save": "Save",
      "common.cancel": "Cancel",
      "common.edit": "Edit",
      "common.delete": "Delete",
      "common.add": "Add",
      "common.search": "Search",
      "common.filter": "Filter",
      "common.export": "Export",
      "common.import": "Import",
      "common.create": "Create",
      "common.update": "Update",
      "common.close": "Close",
      "common.back": "Back",
      "common.next": "Next",
      "common.previous": "Previous",
      "common.yes": "Yes",
      "common.no": "No",
      "common.actions": "Actions",
      "common.details": "Details",
      "common.view": "View",
      "common.manage": "Manage",

      // Company
      "company.name": "TD CONSULTING",
      "company.tagline": "Trusted Recruitment Partner",
    },
    vi: {
      // Navigation
      "nav.dashboard": "Bảng điều khiển",
      "nav.jobs": "Công việc",
      "nav.candidates": "Ứng viên",
      "nav.calendar": "Lịch",
      "nav.email": "Tự động hóa Email",
      "nav.reports": "Báo cáo",
      "nav.notifications": "Thông báo",
      "nav.settings": "Cài đặt",

      // Header
      "header.search": "Tìm kiếm ���ng viên, công việc...",
      "header.quickAdd": "Thêm nhanh",
      "header.addJob": "Thêm công việc",
      "header.addCandidate": "Thêm ứng viên",
      "header.language": "Ngôn ngữ",

      // Dashboard
      "dashboard.title": "Bảng điều khiển",
      "dashboard.subtitle":
        "Chào mừng bạn trở lại! Đây là tổng quan về các hoạt động tuyển dụng của bạn.",
      "dashboard.activeJobs": "Công việc đang tuyển",
      "dashboard.totalCandidates": "Tổng số ứng viên",
      "dashboard.interviewsThisWeek": "Phỏng vấn tuần này",
      "dashboard.avgTimeToHire": "Thời gian tuyển dụng TB",
      "dashboard.totalRevenue": "Tổng doanh thu",
      "dashboard.recentJobs": "Công việc gần đây",
      "dashboard.topCandidates": "Ứng viên hàng đầu",
      "dashboard.recentActivity": "Hoạt động gần đây",
      "dashboard.viewAll": "Xem tất cả",

      // Jobs
      "jobs.title": "Công việc",
      "jobs.subtitle":
        "Quản lý tin tuyển dụng, theo dõi đơn ứng tuyển và tiến độ tuyển dụng.",
      "jobs.createJob": "Tạo công việc",
      "jobs.filterJobs": "Lọc công việc",
      "jobs.position": "Vị trí",
      "jobs.department": "Phòng ban",
      "jobs.applications": "Đơn ứng tuyển",
      "jobs.status": "Trạng thái",
      "jobs.deadline": "Hạn chót",
      "jobs.performance": "Hiệu suất",
      "jobs.recruiter": "Nhà tuyển dụng",
      "jobs.location": "Địa điểm",
      "jobs.priority": "Độ ưu tiên",

      // Candidates
      "candidates.title": "Ứng viên",
      "candidates.subtitle":
        "Quản lý hồ sơ ứng viên, theo dõi tiến độ và lập lịch phỏng vấn.",
      "candidates.addCandidate": "Thêm ứng viên",
      "candidates.moreFilters": "Bộ lọc khác",
      "candidates.name": "Tên",
      "candidates.position": "Vị trí",
      "candidates.stage": "Giai đoạn",
      "candidates.rating": "Đánh giá",
      "candidates.appliedDate": "Ngày ứng tuyển",
      "candidates.source": "Nguồn",

      // Email Automation
      "email.title": "Tự động hóa Email",
      "email.subtitle":
        "Quản lý mẫu email, quy trình làm việc và tự động hóa giao tiếp với ứng viên.",
      "email.newWorkflow": "Quy trình mới",
      "email.newTemplate": "Mẫu mới",
      "email.activeTemplates": "Mẫu đang hoạt động",
      "email.emailsSent": "Email đã gửi (30 ngày)",
      "email.avgOpenRate": "Tỷ lệ mở TB",
      "email.activeWorkflows": "Quy trình đang hoạt động",
      "email.templates": "Mẫu Email",
      "email.workflows": "Quy trình tự động",
      "email.analytics": "Phân tích",
      "email.settings": "Cài đặt",

      // Calendar
      "calendar.title": "Lịch",
      "calendar.subtitle":
        "Lập lịch phỏng vấn, cuộc họp và theo dõi tất cả các cuộc hẹn của bạn.",
      "calendar.scheduleEvent": "Lập lịch sự kiện",
      "calendar.filterEvents": "Lọc sự kiện",
      "calendar.month": "Tháng",
      "calendar.week": "Tuần",
      "calendar.day": "Ngày",
      "calendar.todaySchedule": "Lịch hôm nay",
      "calendar.upcomingEvents": "Sự kiện sắp tới",
      "calendar.eventTypes": "Loại sự kiện",

      // Reports
      "reports.title": "Báo cáo",
      "reports.subtitle":
        "Phân tích hiệu suất tuyển dụng và tạo ra những thông tin chi tiết.",
      "reports.overview": "Tổng quan",
      "reports.performance": "Hiệu suất",
      "reports.sources": "Nguồn",
      "reports.advanced": "Nâng cao",
      "reports.exportReport": "Xuất báo cáo",
      "reports.dateRange": "Khoảng thời gian",

      // Notifications
      "notifications.title": "Thông báo",
      "notifications.subtitle":
        "Cập nhật các hoạt động tuyển dụng quan trọng và cảnh báo hệ thống.",
      "notifications.markAllRead": "Đánh dấu tất cả đã đọc",
      "notifications.filter": "Lọc",
      "notifications.noNotifications": "Không có thông báo",

      // Settings
      "settings.title": "Cài đặt",
      "settings.subtitle":
        "Quản lý tài khoản, tùy chọn và cấu hình hệ thống của bạn.",
      "settings.profile": "Hồ sơ",
      "settings.notifications": "Thông báo",
      "settings.appearance": "Giao diện",
      "settings.security": "Bảo mật",
      "settings.integrations": "Tích hợp",
      "settings.organization": "Tổ chức",
      "settings.personalInfo": "Thông tin cá nhân",
      "settings.preferences": "Tùy chọn",
      "settings.language": "Ngôn ngữ",
      "settings.firstName": "Tên",
      "settings.lastName": "Họ",
      "settings.email": "Địa chỉ Email",
      "settings.phone": "Số điện thoại",
      "settings.jobTitle": "Chức vụ",
      "settings.department": "Phòng ban",
      "settings.saveChanges": "Lưu thay đổi",
      "settings.changePhoto": "Đổi ảnh",
      "settings.remove": "Xóa",
      "settings.exportSettings": "Xuất cài đặt",
      "settings.importSettings": "Nhập cài đặt",

      // Common
      "common.loading": "Đang tải...",
      "common.save": "Lưu",
      "common.cancel": "Hủy",
      "common.edit": "Sửa",
      "common.delete": "Xóa",
      "common.add": "Thêm",
      "common.search": "Tìm kiếm",
      "common.filter": "Lọc",
      "common.export": "Xuất",
      "common.import": "Nhập",
      "common.create": "Tạo",
      "common.update": "Cập nhật",
      "common.close": "Đóng",
      "common.back": "Quay lại",
      "common.next": "Tiếp theo",
      "common.previous": "Trước đó",
      "common.yes": "Có",
      "common.no": "Không",
      "common.actions": "Hành động",
      "common.details": "Chi tiết",
      "common.view": "Xem",
      "common.manage": "Quản lý",

      // Dashboard Hardcoded Text
      "dashboard.filter": "Lọc",
      "dashboard.newJob": "Công việc mới",
      "dashboard.vsLastMonth": "so với tháng trước",
      "dashboard.recruitmentPipeline": "Quy trình tuyển dụng",
      "dashboard.quickStats": "Thống kê nhanh",
      "dashboard.costPerHire": "Chi phí mỗi lần tuyển",
      "dashboard.hiringSuccessRate": "Tỷ lệ tuyển dụng thành công",
      "dashboard.sourceEffectiveness": "Hiệu quả nguồn",
      "dashboard.pendingInterviews": "Phỏng vấn đang chờ",
      "dashboard.recentJobPostings": "Tin tuyển dụng gần đây",
      "dashboard.jobTitle": "Tiêu đề công việc",
      "dashboard.department": "Phòng ban",
      "dashboard.applicants": "Ứng viên",
      "dashboard.status": "Trạng thái",
      "dashboard.priority": "Độ ưu tiên",
      "dashboard.active": "Đang hoạt động",
      "dashboard.draft": "Bản nháp",
      "dashboard.high": "Cao",
      "dashboard.medium": "Trung bình",
      "dashboard.low": "Thấp",
      "dashboard.applied": "Đã ứng tuyển",
      "dashboard.screening": "Sàng lọc",
      "dashboard.interview": "Phỏng vấn",
      "dashboard.offer": "Đề nghị",
      "dashboard.hired": "Đã tuyển",

      // Candidates Page
      "candidates.totalCandidates": "Tổng số ứng viên",
      "candidates.activePipeline": "Quy trình đang hoạt động",
      "candidates.interviewsScheduled": "Phỏng vấn đã lên lịch",
      "candidates.offersExtended": "Đề nghị đã gửi",
      "candidates.list": "Danh sách",
      "candidates.grid": "Lưới",
      "candidates.fields": "Trường",
      "candidates.searchPlaceholder":
        "Tìm kiếm ứng viên theo tên, vị trí, kỹ năng...",
      "candidates.allDepartments": "Tất cả phòng ban",
      "candidates.allStages": "Tất cả giai đoạn",
      "candidates.allRecruiters": "Tất cả nhà tuyển dụng",
      "candidates.candidateName": "Tên ứng viên",
      "candidates.appliedOn": "Ngày ứng tuyển",
      "candidates.email": "Email",
      "candidates.phone": "Điện tho���i",
      "candidates.jobPosition": "Vị trí công việc",
      "candidates.recruiter": "Nhà tuyển dụng",
      "candidates.currentStage": "Giai đoạn hiện tại",
      "candidates.source": "Nguồn",
      "candidates.salary": "Lương",
      "candidates.location": "Địa điểm",
      "candidates.actions": "Hành động",
      "candidates.viewDetails": "Xem chi tiết",
      "candidates.editCandidate": "Sửa ứng viên",
      "candidates.downloadCV": "Tải CV",
      "candidates.shareProfile": "Chia sẻ hồ sơ",
      "candidates.removeCandidate": "Xóa ứng viên",
      "candidates.noCandidates": "Không có ứng viên",
      "candidates.previous": "Trước",
      "candidates.next": "Tiếp theo",
      "candidates.fullName": "Họ và tên",
      "candidates.city": "Thành phố, Tỉnh",
      "candidates.selectPosition": "Chọn vị trí",
      "candidates.selectDepartment": "Chọn phòng ban",
      "candidates.selectSource": "Chọn nguồn",
      "candidates.uploadResume": "Tải lên CV/Hồ sơ",
      "candidates.automaticExtraction":
        "Chúng tôi sẽ tự động trích xuất thông tin ứng viên từ CV",
      "candidates.chooseFile": "Chọn tệp",
      "candidates.chooseFiles": "Chọn tệp tin",
      "candidates.singleResume": "CV đơn lẻ",
      "candidates.multipleResumes": "Nhiều CV",
      "candidates.uploadResumes": "Tải lên CV/Hồ sơ",
      "candidates.uploadMultiple":
        "Tải lên nhiều CV và gán chúng vào một vị trí công việc",
      "candidates.selectPositionAll": "Chọn vị trí cho tất cả CV",
      "candidates.selectSourceAll": "Chọn vị trí cho tất cả CV (Tùy chọn)",
      "candidates.uploadedFiles": "Tệp đã tải lên",
      "candidates.createCandidate": "Tạo ứng viên",
      "candidates.createCandidates": "Tạo ứng viên",
      "candidates.manualEntry": "Nhập thủ công",
      "candidates.uploadResumeTab": "Tải lên CV",
      "candidates.addNewCandidate": "Thêm ứng viên mới",
      "candidates.createCandidateProfile":
        "Tạo hồ sơ ứng viên mới thủ công hoặc tải lên CV của họ.",
      "candidates.experienceLevel": "Mức độ kinh nghiệm",
      "candidates.anyExperience": "Bất kỳ kinh nghiệm nào",
      "candidates.entryLevel": "Cấp độ mới (0-2 năm)",
      "candidates.midLevel": "Cấp độ trung (3-5 năm)",
      "candidates.seniorLevel": "Cấp độ cao (5+ năm)",
      "candidates.salaryRange": "Khoảng lương",
      "candidates.anySalary": "Bất kỳ mức lương nào",
      "candidates.50to75k": "$50k - $75k",
      "candidates.75to100k": "$75k - $100k",
      "candidates.100to150k": "$100k - $150k",
      "candidates.150kPlus": "$150k+",
      "candidates.rating": "Đánh giá",
      "candidates.anyRating": "Bất kỳ đánh giá nào",
      "candidates.5stars": "5 sao",
      "candidates.4plusStars": "4+ sao",
      "candidates.3plusStars": "3+ sao",
      "candidates.applicationDate": "Ngày ứng tuyển",
      "candidates.anyDate": "Bất kỳ ngày nào",
      "candidates.lastWeek": "Tuần trước",
      "candidates.lastMonth": "Tháng trước",
      "candidates.lastQuarter": "Quý trước",
      "candidates.skills": "Kỹ năng",
      "candidates.searchBySkills": "Tìm kiếm theo kỹ năng cụ thể...",
      "candidates.applyFilters": "Áp dụng bộ lọc",
      "candidates.filtersApplied": "Đã áp dụng bộ lọc",
      "candidates.advancedFiltersDescription":
        "Bộ lọc nâng cao đã được áp dụng cho danh sách ứng viên.",
      "candidates.advancedFilters": "Bộ lọc nâng cao",
      "candidates.additionalFilters":
        "Áp dụng bộ lọc bổ sung để tinh chỉnh tìm kiếm ứng viên của bạn.",
      "candidates.daysInStage": "ngày trong giai đoạn",

      // Jobs Page
      "jobs.activeJobs": "Công việc đang hoạt động",
      "jobs.totalApplications": "Tổng số đơn ứng tuyển",
      "jobs.positionsFilled": "Vị trí đã tuyển",
      "jobs.avgTimeToFill": "Thời gian tuyển TB",
      "jobs.days": "ngày",
      "jobs.exportReport": "Xuất báo cáo",
      "jobs.addNewJob": "Thêm công việc mới",
      "jobs.columns": "Cột",
      "jobs.searchJobs":
        "Tìm kiếm công việc theo vị trí, phòng ban, nhà tuyển dụng...",
      "jobs.allStatus": "Tất cả trạng thái",
      "jobs.open": "Mở",
      "jobs.closed": "Đóng",
      "jobs.inProgress": "Đang tiến hành",
      "jobs.paused": "Tạm dừng",
      "jobs.allPriority": "Tất cả độ ưu tiên",
      "jobs.moreFilters": "Bộ lọc khác",
      "jobs.target": "Mục tiêu",
      "jobs.process": "Quy trình",
      "jobs.openDate": "Ngày mở",
      "jobs.deadline": "Hạn chót",
      "jobs.estimatedCost": "Chi phí ước tính",
      "jobs.actualCost": "Chi phí thực tế",
      "jobs.editJob": "Sửa công việc",
      "jobs.share": "Chia sẻ",
      "jobs.delete": "Xóa",
      "jobs.deleteJob": "Xóa công việc",
      "jobs.confirmDelete":
        'Bạn có chắc chắn muốn xóa "{position}"? Hành động này không thể hoàn tác.',
      "jobs.jobCreated": "Đã tạo công việc",
      "jobs.jobCreatedDesc": '"{position}" đã được tạo thành công.',
      "jobs.jobUpdated": "Đã cập nhật công việc",
      "jobs.jobUpdatedDesc": '"{position}" đã được cập nhật thành công.',
      "jobs.jobDeleted": "Đã xóa công việc",
      "jobs.jobDeletedDesc": "Công việc đã được xóa thành công.",
      "jobs.error": "Lỗi",
      "jobs.createError": "Không thể tạo công việc. Vui lòng thử lại.",
      "jobs.updateError": "Không thể cập nhật công việc. Vui lòng thử lại.",
      "jobs.deleteError": "Không thể xóa công việc. Vui lòng thử lại.",
      "jobs.shareJob": "Chia sẻ công việc",
      "jobs.generateLink": "Tạo liên kết chia sẻ cho tin tuyển dụng này.",
      "jobs.linkCopied": "Đã sao chép liên kết",
      "jobs.linkCopiedDesc":
        "Liên kết chia sẻ công việc đã được sao chép vào clipboard.",
      "jobs.copy": "Sao chép",
      "jobs.close": "Đóng",
      "jobs.addNewJobTitle": "Thêm công việc mới",
      "jobs.editJobTitle": "Sửa công việc",
      "jobs.updateJobDetails": "Cập nhật chi tiết công việc bên dưới.",
      "jobs.createJobDetails":
        "Tạo tin tuyển dụng mới với tất cả các chi tiết cần thiết.",
      "jobs.basicInfo": "Thông tin cơ bản",
      "jobs.jobDetails": "Chi tiết công việc",
      "jobs.teamBudget": "Nhóm & Ngân sách",
      "jobs.emailAlias": "Bí danh Email",
      "jobs.emailPlaceholder": "jobs@company.com",
      "jobs.jobLocation": "Địa điểm làm việc",
      "jobs.locationPlaceholder": "San Francisco, CA hoặc Từ xa",
      "jobs.positionPlaceholder": "Kỹ sư phần mềm cấp cao",
      "jobs.employmentType": "Loại hình việc làm",
      "jobs.selectEmploymentType": "Chọn loại hình việc làm",
      "jobs.fullTime": "Toàn thời gian",
      "jobs.partTime": "Bán thời gian",
      "jobs.contract": "Hợp đồng",
      "jobs.domainIndustry": "Lĩnh vực/Ngành nghề",
      "jobs.domainPlaceholder": "Công nghệ, Tài chính, Y tế",
      "jobs.selectPriority": "Chọn độ ưu tiên",
      "jobs.expectedSkills": "Kỹ năng mong đợi",
      "jobs.skillsPlaceholder":
        "React, TypeScript, Node.js (cách nhau bằng dấu phẩy)",
      "jobs.salaryMin": "Lương tối thiểu",
      "jobs.salaryMax": "Lương tối đa",
      "jobs.jobDescription": "Mô tả công việc",
      "jobs.descriptionPlaceholder": "Mô tả vai trò, trách nhiệm và yêu cầu...",
      "jobs.headcount": "Số lượng người cần tuyển",
      "jobs.selectRecruiter": "Chọn nhà tuyển dụng",
      "jobs.interviewers": "Người phỏng vấn",
      "jobs.interviewersPlaceholder":
        "Chọn thành viên nhóm sẽ tiến hành phỏng vấn",
      "jobs.estimatedBudget": "Ngân sách ước tính",
      "jobs.createJob": "Tạo công việc",
      "jobs.updateJob": "Cập nhật công việc",
      "jobs.pipelineSummary": "Tóm tắt quy trình",
      "jobs.interviewing": "Đang phỏng vấn",
      "jobs.applied": "Đã ứng tuyển",
      "jobs.interview": "Phỏng vấn",
      "jobs.hired": "Đã tuyển",

      // Calendar Page
      "calendar.filterEvents": "Lọc sự kiện",
      "calendar.scheduleEvent": "Lập lịch sự kiện",
      "calendar.scheduleNewEvent": "Lập lịch sự kiện mới",
      "calendar.createEvent": "Tạo phỏng vấn, cuộc họp hoặc cuộc hẹn mới.",
      "calendar.eventType": "Loại sự kiện",
      "calendar.selectType": "Chọn loại",
      "calendar.technicalInterview": "Phỏng vấn kỹ thuật",
      "calendar.phoneScreening": "Sàng lọc qua điện thoại",
      "calendar.finalRound": "Vòng cuối",
      "calendar.teamMeeting": "Họp nhóm",
      "calendar.offerDiscussion": "Thảo luận đề nghị",
      "calendar.meetingType": "Loại cuộc họp",
      "calendar.selectFormat": "Chọn định dạng",
      "calendar.inPerson": "Trực tiếp",
      "calendar.videoCall": "Cuộc gọi video",
      "calendar.phoneCall": "Cuộc gọi điện thoại",
      "calendar.eventTitle": "Tiêu đề sự kiện",
      "calendar.eventTitlePlaceholder":
        "ví dụ: Phỏng vấn kỹ thuật - Nguyễn Văn A",
      "calendar.date": "Ngày",
      "calendar.duration": "Thời lượng",
      "calendar.selectDuration": "Chọn thời lượng",
      "calendar.15minutes": "15 phút",
      "calendar.30minutes": "30 phút",
      "calendar.45minutes": "45 phút",
      "calendar.1hour": "1 giờ",
      "calendar.1point5hours": "1.5 giờ",
      "calendar.2hours": "2 giờ",
      "calendar.startTime": "Thời gian bắt đầu",
      "calendar.locationLink": "Địa điểm/Liên kết",
      "calendar.locationPlaceholder": "Phòng họp A hoặc liên kết Zoom",
      "calendar.participants": "Người tham gia",
      "calendar.participantsPlaceholder": "Thêm người tham gia bằng email",
      "calendar.notes": "Ghi chú",
      "calendar.notesPlaceholder":
        "Ghi chú bổ sung hoặc các mục chương trình...",
      "calendar.january2024": "Tháng 1 năm 2024",
      "calendar.month": "Tháng",
      "calendar.week": "Tuần",
      "calendar.day": "Ngày",
      "calendar.sun": "CN",
      "calendar.mon": "T2",
      "calendar.tue": "T3",
      "calendar.wed": "T4",
      "calendar.thu": "T5",
      "calendar.fri": "T6",
      "calendar.sat": "T7",
      "calendar.noEvents": "Không có sự kiện",
      "calendar.todaySchedule": "Lịch hôm nay",
      "calendar.totalEvents": "Tổng số sự kiện",
      "calendar.interviews": "Phỏng vấn",
      "calendar.meetings": "Cuộc họp",
      "calendar.freeTime": "Thời gian rảnh",
      "calendar.4hours": "4 giờ",
      "calendar.upcomingEvents": "Sự kiện sắp tới",
      "calendar.editEvent": "Sửa sự kiện",
      "calendar.viewAttendees": "Xem người tham gia",
      "calendar.cancelEvent": "Hủy sự kiện",
      "calendar.eventTypes": "Loại sự kiện",
      "calendar.eventsOn": "Sự kiện vào ngày {date}",

      // Email Automation Page
      "email.newWorkflow": "Quy trình mới",
      "email.newTemplate": "Mẫu mới",
      "email.createEmailWorkflow": "Tạo quy trình Email",
      "email.setupAutomatedSequence":
        "Thiết lập chuỗi email tự động cho ứng viên.",
      "email.workflowName": "Tên quy trình",
      "email.workflowNamePlaceholder": "ví dụ: Theo dõi phỏng vấn",
      "email.triggerEvent": "Sự kiện kích hoạt",
      "email.selectTrigger": "Chọn kích hoạt",
      "email.applicationReceived": "Nhận được đơn ứng tuyển",
      "email.screeningCompleted": "Hoàn thành sàng lọc",
      "email.interviewScheduled": "Đã lên lịch phỏng vấn",
      "email.offerExtended": "Đã gửi đề nghị",
      "email.applicationRejected": "Đơn ứng tuyển bị từ chối",
      "email.description": "Mô tả",
      "email.descriptionPlaceholder": "Mô tả ngắn gọn về quy trình này...",
      "email.createWorkflow": "Tạo quy trình",
      "email.createEmailTemplate": "Tạo mẫu Email",
      "email.createTemplateDesc":
        "Tạo mẫu email mới để giao tiếp với ứng viên.",
      "email.templateName": "Tên mẫu",
      "email.templateNamePlaceholder": "ví dụ: Xác nhận phỏng vấn",
      "email.templateType": "Loại mẫu",
      "email.selectType": "Chọn loại",
      "email.autoResponse": "Phản hồi tự động",
      "email.interviewRelated": "Liên quan đến phỏng vấn",
      "email.jobOffer": "Đề nghị việc làm",
      "email.rejection": "Từ chối",
      "email.reminder": "Nhắc nhở",
      "email.followUp": "Theo dõi",
      "email.subjectLine": "Dòng tiêu đề",
      "email.subjectPlaceholder":
        "ví dụ: Đã lên lịch phỏng vấn cho vị trí {{job_title}}",
      "email.emailContent": "Nội dung Email",
      "email.contentPlaceholder":
        "Kính gửi {{candidate_name}},\n\nNội dung email của bạn ở đây...\n\nTrân trọng,\nĐội ngũ {{company_name}}",
      "email.availableVariables": "Biến có sẵn",
      "email.createTemplate": "Tạo mẫu",
      "email.emailTemplates": "Mẫu Email",
      "email.automationWorkflows": "Quy trình tự động",
      "email.analytics": "Phân tích",
      "email.settings": "Cài đặt",
      "email.active": "Đang hoạt động",
      "email.usage30d": "Sử dụng (30 ngày):",
      "email.openRate": "Tỷ lệ mở:",
      "email.trigger": "Kích hoạt:",
      "email.edit": "Sửa",
      "email.editEmailTemplate": "Sửa mẫu Email",
      "email.updateTemplate": "Cập nhật nội dung và cài đặt mẫu email của bạn.",
      "email.saveChanges": "Lưu thay đổi",
      "email.steps": "Bước",
      "email.activeCandidates": "Ứng viên đang hoạt động",
      "email.emailPerformance": "Hiệu suất Email",
      "email.totalEmailsSent": "Tổng số Email đã gửi",
      "email.averageOpenRate": "Tỷ lệ mở trung bình",
      "email.averageClickRate": "Tỷ lệ click trung bình",
      "email.bounceRate": "Tỷ lệ bounce",
      "email.topPerformingTemplates": "Mẫu hiệu suất cao nhất",
      "email.sent": "đã gửi",
      "email.open": "mở",
      "email.emailSettings": "Cài đặt Email",
      "email.autoSendAcknowledgments": "Tự động gửi xác nhận",
      "email.autoSendDesc": "Tự động gửi email xác nhận khi ứng viên ứng tuyển",
      "email.interviewReminders": "Nhắc nhở phỏng vấn",
      "email.reminderDesc": "Gửi email nhắc nhở 24 giờ trước phỏng vấn",
      "email.statusChangeNotifications": "Thông báo thay đổi trạng thái",
      "email.statusChangeDesc":
        "Thông báo cho ứng viên khi trạng thái đơn ứng tuyển thay đổi",
      "email.senderInformation": "Thông tin người gửi",
      "email.fromName": "Tên người gửi",
      "email.fromEmail": "Email người gửi",
      "email.replyToEmail": "Email phản hồi",
      "email.saveSettings": "Lưu cài đặt",

      // Reports Page
      "reports.exportReport": "Xuất báo cáo",
      "reports.dateRange": "Khoảng thời gian",
      "reports.last7days": "7 ngày qua",
      "reports.last30days": "30 ngày qua",
      "reports.last90days": "90 ngày qua",
      "reports.lastYear": "Năm qua",
      "reports.job": "C��ng việc",
      "reports.allJobs": "Tất cả công việc",
      "reports.recruiter": "Nhà tuyển dụng",
      "reports.allRecruiters": "Tất cả nhà tuyển dụng",
      "reports.totalApplications": "Tổng số đơn ứng tuyển",
      "reports.conversionRate": "Tỷ lệ chuyển đổi",
      "reports.avgTimeToHire": "Thời gian tuyển TB",
      "reports.costPerHire": "Chi phí mỗi lần tuyển",
      "reports.conversionFunnel": "Phễu chuyển đổi",
      "reports.monthlyTrends": "Xu hướng hàng tháng",
      "reports.recruiterPerformance": "Hiệu suất nhà tuyển dụng",
      "reports.jobPerformanceComparison": "So sánh hiệu suất công việc",
      "reports.detailedRecruiterMetrics": "Chỉ số chi tiết nhà tuyển dụng",
      "reports.effectivenessScore": "Điểm hiệu quả",
      "reports.applicationSources": "Nguồn đơn ứng tuyển",
      "reports.sourceEffectiveness": "Hiệu quả nguồn",
      "reports.sourcePerformanceDetails": "Chi tiết hiệu suất nguồn",
      "reports.effective": "Hiệu quả",
      "reports.applicationFrequencyHeatmap":
        "Bản đồ nhiệt tần suất đơn ứng tuyển",
      "reports.monday": "Thứ hai",
      "reports.tuesday": "Thứ ba",
      "reports.wednesday": "Thứ tư",
      "reports.thursday": "Thứ năm",
      "reports.friday": "Thứ sáu",
      "reports.9am": "9 giờ sáng",
      "reports.2pm": "2 giờ chiều",
      "reports.pipelineVelocity": "Tốc độ quy trình",
      "reports.averageStageDuration": "Thời lượng giai đoạn trung bình",
      "reports.screeningToInterview": "Sàng lọc → Phỏng vấn",
      "reports.interviewToOffer": "Phỏng vấn → Đề nghị",
      "reports.qualityScore": "Điểm chất lượng",
      "reports.candidateQualityRating": "Đánh giá chất lượng ứng viên",
      "reports.quality": "Chất lượng",
      "reports.automationRate": "Tỷ lệ tự động hóa",
      "reports.automatedCommunications": "Giao tiếp tự động",
      "reports.emailResponses": "Phản hồi email",
      "reports.stageUpdates": "Cập nhật giai đoạn",
      "reports.applications": "đơn ứng tuyển",
      "reports.interviews": "phỏng vấn",
      "reports.hires": "tuyển dụng",
      "reports.jobA": "Công việc A",
      "reports.jobB": "Công việc B",
      "reports.applicationVolume": "Khối lượng đơn ứng tuyển",
      "reports.qualityScoreRadar": "Điểm chất lượng",
      "reports.timeToFill": "Thời gian tuyển",
      "reports.costEfficiency": "Hiệu quả chi phí",
      "reports.candidateSatisfaction": "Sự hài lòng của ứng viên",
      "reports.applications": "Đơn ứng tuyển",
      "reports.interviews": "Phỏng vấn",
      "reports.hires": "Tuy���n dụng",
      "reports.effectivenessPercent": "Hiệu quả %",
      "reports.days": "ngày",

      // Settings Page
      "settings.personalInfo": "Thông tin cá nhân",
      "settings.changePhoto": "Đổi ảnh",
      "settings.remove": "Xóa",
      "settings.firstName": "Tên",
      "settings.lastName": "Họ",
      "settings.emailAddress": "Địa chỉ Email",
      "settings.phoneNumber": "Số điện thoại",
      "settings.jobTitle": "Chức vụ",
      "settings.humanResources": "Nhân sự",
      "settings.engineering": "Kỹ thuật",
      "settings.product": "Sản phẩm",
      "settings.design": "Thiết kế",
      "settings.marketing": "Marketing",
      "settings.saveChanges": "Lưu thay đổi",
      "settings.preferences": "Tùy chọn",
      "settings.timezone": "Múi giờ",
      "settings.pacificStandardTime": "Giờ chuẩn Thái Bình Dương",
      "settings.easternStandardTime": "Giờ chuẩn Đông",
      "settings.centralStandardTime": "Giờ chuẩn Trung tâm",
      "settings.mountainStandardTime": "Giờ chuẩn Núi",
      "settings.utc": "UTC",
      "settings.dateFormat": "Định dạng ngày",
      "settings.currency": "Tiền tệ",
      "settings.autoSaveDrafts": "Tự động lưu bản nháp",
      "settings.autoSaveDesc": "Tự động lưu bản nháp biểu mẫu",
      "settings.savePreferences": "Lưu tùy chọn",
      "settings.notificationSettings": "Cài đặt thông báo",
      "settings.emailNotifications": "Thông báo Email",
      "settings.newApplications": "Đơn ứng tuyển mới",
      "settings.newApplicationsDesc": "Nhận thông báo khi ứng viên ứng tuyển",
      "settings.interviewReminders": "Nhắc nhở phỏng vấn",
      "settings.interviewRemindersDesc": "Nhắc nhở 24 giờ trước phỏng vấn",
      "settings.statusUpdates": "Cập nhật trạng thái",
      "settings.statusUpdatesDesc": "Khi trạng thái ứng viên thay đổi",
      "settings.weeklyReports": "Báo cáo hàng tuần",
      "settings.weeklyReportsDesc": "Tóm tắt các hoạt động tuyển dụng",
      "settings.pushNotifications": "Thông báo đẩy",
      "settings.urgentUpdates": "Cập nhật khẩn cấp",
      "settings.urgentUpdatesDesc": "Cảnh báo và cập nhật hệ thống quan trọng",
      "settings.calendarEvents": "Sự kiện lịch",
      "settings.calendarEventsDesc": "Phỏng vấn và cuộc họp sắp tới",
      "settings.teamMessages": "Tin nhắn nhóm",
      "settings.teamMessagesDesc": "Tin nhắn từ thành viên nhóm",
      "settings.notificationFrequency": "Tần suất thông báo",
      "settings.emailDigest": "Tóm tắt Email",
      "settings.realTime": "Thời gian thực",
      "settings.hourly": "Hàng giờ",
      "settings.daily": "Hàng ngày",
      "settings.weekly": "Hàng tuần",
      "settings.never": "Không bao giờ",
      "settings.appearanceTheme": "Giao diện & Chủ đề",
      "settings.theme": "Chủ đề",
      "settings.light": "Sáng",
      "settings.dark": "Tối",
      "settings.system": "Hệ thống",
      "settings.layout": "Bố cục",
      "settings.compactMode": "Chế độ nén",
      "settings.compactModeDesc":
        "Giảm khoảng cách để hiển thị nhiều nội dung hơn",
      "settings.showSidebar": "Hiển thị thanh bên",
      "settings.showSidebarDesc": "Luôn hiển thị thanh điều hướng bên",
      "settings.fontSettings": "Cài đặt phông chữ",
      "settings.fontSize": "Kích thước phông chữ",
      "settings.small": "Nhỏ",
      "settings.large": "Lớn",
      "settings.securitySettings": "Cài đặt bảo mật",
      "settings.currentPassword": "Mật khẩu hiện tại",
      "settings.newPassword": "Mật khẩu mới",
      "settings.confirmNewPassword": "Xác nhận mật khẩu mới",
      "settings.updatePassword": "Cập nhật mật khẩu",
      "settings.twoFactorAuth": "Xác thực hai yếu tố",
      "settings.2faStatus": "Trạng thái 2FA",
      "settings.2faDesc": "Tăng cường bảo mật tài khoản",
      "settings.disabled": "Vô hiệu hóa",
      "settings.enable2fa": "Bật 2FA",
      "settings.activeSessions": "Phiên hoạt động",
      "settings.currentSession": "Phiên hiện tại",
      "settings.chromeOnMacos": "Chrome trên macOS",
      "settings.thirdPartyIntegrations": "Tích hợp bên thứ ba",
      "settings.googleCalendar": "Google Calendar",
      "settings.googleCalendarDesc": "Đồng bộ phỏng vấn và cuộc họp",
      "settings.slack": "Slack",
      "settings.slackDesc": "Thông báo và cập nhật nhóm",
      "settings.zoom": "Zoom",
      "settings.zoomDesc": "Tích hợp phỏng vấn video",
      "settings.linkedin": "LinkedIn",
      "settings.linkedinDesc": "Nhập hồ sơ ứng viên",
      "settings.github": "GitHub",
      "settings.githubDesc": "Tích hợp đánh giá kỹ thuật",
      "settings.microsoftTeams": "Microsoft Teams",
      "settings.microsoftTeamsDesc": "Nền tảng cuộc họp video thay thế",
      "settings.connected": "Đã kết nối",
      "settings.disconnected": "Chưa kết nối",
      "settings.connect": "Kết nối",
      "settings.disconnect": "Ngắt kết nối",
      "settings.organizationSettings": "Cài đặt tổ chức",
      "settings.companyName": "Tên công ty",
      "settings.companyWebsite": "Website công ty",
      "settings.companySize": "Quy mô công ty",
      "settings.1to10employees": "1-10 nhân viên",
      "settings.11to50employees": "11-50 nhân viên",
      "settings.50to200employees": "50-200 nhân viên",
      "settings.200to1000employees": "200-1000 nhân viên",
      "settings.1000plusEmployees": "1000+ nhân viên",
      "settings.industry": "Ngành nghề",
      "settings.technology": "Công nghệ",
      "settings.finance": "Tài chính",
      "settings.healthcare": "Y tế",
      "settings.education": "Giáo dục",
      "settings.retail": "Bán lẻ",
      "settings.other": "Khác",
      "settings.saveOrganizationSettings": "Lưu cài đặt tổ chức",
      "settings.teamManagement": "Quản lý nhóm",
      "settings.teamMembers": "Thành viên nhóm",
      "settings.teamMembersDesc":
        "Quản lý quyền truy cập và phân quyền người dùng",
      "settings.inviteMember": "Mời thành viên",
      "settings.admin": "Quản trị viên",

      // Common UI Elements
      "common.loading": "Đang tải...",
      "common.save": "Lưu",
      "common.cancel": "Hủy",
      "common.edit": "Sửa",
      "common.delete": "Xóa",
      "common.add": "Thêm",
      "common.search": "Tìm kiếm",
      "common.filter": "Lọc",
      "common.export": "Xuất",
      "common.import": "Nhập",
      "common.create": "Tạo",
      "common.update": "Cập nhật",
      "common.close": "Đóng",
      "common.back": "Quay lại",
      "common.next": "Tiếp theo",
      "common.previous": "Trước đó",
      "common.yes": "Có",
      "common.no": "Không",
      "common.actions": "Hành động",
      "common.details": "Chi tiết",
      "common.view": "Xem",
      "common.manage": "Quản lý",

      // Company
      "company.name": "TD CONSULTING",
      "company.tagline": "Đối tác Tuyển dụng Đáng tin cậy",
    },
    zh: {
      "nav.dashboard": "仪表板",
      "nav.jobs": "职位",
      "nav.candidates": "候选人",
      "nav.calendar": "日历",
      "nav.email": "邮件自动化",
      "nav.reports": "报告",
      "nav.notifications": "通知",
      "nav.settings": "设置",
      "company.name": "TD CONSULTING",
      "company.tagline": "值得���赖的招聘合作伙伴",
    },
    ja: {
      "nav.dashboard": "ダッシュボード",
      "nav.jobs": "求人",
      "nav.candidates": "候補者",
      "nav.calendar": "カレンダー",
      "nav.email": "メール自動化",
      "nav.reports": "レポート",
      "nav.notifications": "通知",
      "nav.settings": "設定",
      "company.name": "TD CONSULTING",
      "company.tagline": "信頼できる採用パートナー",
    },
    ko: {
      "nav.dashboard": "대시보드",
      "nav.jobs": "채용",
      "nav.candidates": "후보자",
      "nav.calendar": "캘린더",
      "nav.email": "이메일 자동화",
      "nav.reports": "보고서",
      "nav.notifications": "알림",
      "nav.settings": "설정",
      "company.name": "TD CONSULTING",
      "company.tagline": "신뢰할 수 있는 채용 파트너",
    },
    th: {
      "nav.dashboard": "แดชบอร์ด",
      "nav.jobs": "งาน",
      "nav.candidates": "ผู้สมัคร",
      "nav.calendar": "ปฏิทิน",
      "nav.email": "ระบบอีเมลอัตโนมัติ",
      "nav.reports": "รายงาน",
      "nav.notifications": "การแจ้งเตือน",
      "nav.settings": "การตั้งค่า",
      "company.name": "TD CONSULTING",
      "company.tagline": "พันธมิตรการสรรหาที่เชื่อถือได้",
    },
    fr: {
      "nav.dashboard": "Tableau de bord",
      "nav.jobs": "Emplois",
      "nav.candidates": "Candidats",
      "nav.calendar": "Calendrier",
      "nav.email": "Automatisation Email",
      "nav.reports": "Rapports",
      "nav.notifications": "Notifications",
      "nav.settings": "Paramètres",
      "company.name": "TD CONSULTING",
      "company.tagline": "Partenaire de recrutement de confiance",
    },
    es: {
      "nav.dashboard": "Panel de control",
      "nav.jobs": "Trabajos",
      "nav.candidates": "Candidatos",
      "nav.calendar": "Calendario",
      "nav.email": "Automatización de correo",
      "nav.reports": "Informes",
      "nav.notifications": "Notificaciones",
      "nav.settings": "Configuración",
      "company.name": "TD CONSULTING",
      "company.tagline": "Socio de reclutamiento confiable",
    },
  };

  return (key: string, fallback?: string) => {
    return translations[language]?.[key] || fallback || key;
  };
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [currentLanguage, setCurrentLanguage] = useState<Language>(() => {
    const stored = localStorage.getItem(STORAGE_KEY);
    return (stored as Language) || "en";
  });

  const t = useTranslations(currentLanguage);

  const setLanguage = (language: Language) => {
    setCurrentLanguage(language);
    localStorage.setItem(STORAGE_KEY, language);

    // Update document language
    document.documentElement.lang = language;
  };

  const getCurrentLanguageInfo = (): LanguageOption => {
    return (
      SUPPORTED_LANGUAGES.find((lang) => lang.code === currentLanguage) ||
      SUPPORTED_LANGUAGES[0]
    );
  };

  useEffect(() => {
    document.documentElement.lang = currentLanguage;
  }, [currentLanguage]);

  return (
    <LanguageContext.Provider
      value={{
        currentLanguage,
        setLanguage,
        t,
        getCurrentLanguageInfo,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
